In [174]:
import numpy as np

In [175]:
# Define a square matrix

# A = np.array([[2,4],[1,2]])

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


In [176]:
# Compute Transpose

A_transpose = np.transpose(A) # or A.T

In [177]:
A_inv_trans = np.linalg.det(A)

print(A_inv_trans)

-9.51619735392994e-16


In [178]:
# Compute Determinant
det_A = np.linalg.det(A)

print(det_A)


-9.51619735392994e-16


In [179]:
# B = np.array([[1,6],[1,6]])

# B_det = np.linalg.det(B)

# print(B_det)

# B_inverse = np.linalg.inv(B)  # Only works if det(B) ≠ 0

# B_inverse

In [180]:
# Check if the matrix is invertible

if det_A != 0:
    
    A_inverse = np.linalg.inv(A)
    identity_matrix = np.dot(A, A_inverse)
    print("Inverse of A:\n", A_inverse)
    print("A * A_inverse (Should be Identity Matrix):\n", identity_matrix)
else:
    print("Matrix A is singular (determinant = 0), so no inverse exists.")

Inverse of A:
 [[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
A * A_inverse (Should be Identity Matrix):
 [[ 0.  1.  0.]
 [ 0.  2.  0.]
 [-4.  3.  2.]]


 Next Challenge: Condition Number (Numerical Stability)
 
Even if a matrix has an inverse, some matrices are ill-conditioned, meaning their inverse can be highly unstable in numerical computations.

In [181]:
B = np.array([[3, 5], [1, 2]])

C = np.array([[1, 2], [2.0001, 4]])

In [182]:
cond_B = np.linalg.cond(B)

cond_C = np.linalg.cond(C)

print(np.linalg.det(B))

1.0000000000000004


In [183]:
print(cond_B)

print(cond_C)

38.974342094150494
125002.00004075332
