In [140]:
import numpy as np

In [141]:
A = np.array([[3,5],[1,2]])

B = np.array([[1,2],[2,4]])

In [142]:
# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

P = eigenvectors

D = np.diag(eigenvalues)

det_P = np.linalg.det(P)

P_inverse = np.linalg.inv(P)

In [143]:
print(f'Matrix A : \n{A} ')

print(f'Eigen Vectors : \n{P} ')

print(f'Diagonal  Matrix D : \n{D} ')

print(f'Determinant of P:\n {det_P}')

print(f'Inverse of P (P^-1): \n {P_inverse}')


Matrix A : 
[[3 5]
 [1 2]] 
Eigen Vectors : 
[[ 0.94140906 -0.87315384]
 [ 0.33726692  0.48744474]] 
Diagonal  Matrix D : 
[[4.79128785 0.        ]
 [0.         0.20871215]] 
Determinant of P:
 0.7533708035008841
Inverse of P (P^-1): 
 [[ 0.64701836  1.15899612]
 [-0.44767719  1.24959589]]


In [144]:
A_reconstructed = P @ D @ P_inverse

#Check if matrices are the same.

print("\nVerification (A == PDP^-1):")

print(np.allclose(A, A_reconstructed))


Verification (A == PDP^-1):
True
