SVD is one of the most powerful matrix factorizations in linear algebra, widely used in machine learning, computer vision, recommendation systems, and deep learning. To truly understand SVD, let’s break it down into digestible parts.

Singular Value Decomposition (SVD) is a way to break down any matrix into three simpler matrices that reveal its fundamental properties.

A=UΣVT
 
 U (m × m) → Left singular vectors (columns are orthonormal)

Σ (m × n) → Diagonal matrix of singular values (like eigenvalues)

V ^T (n × n) → Right singular vectors (rows are orthonormal)



For a matrix A:
1️⃣ Compute eigenvalues & eigenvectors of 

A^TA (gives V)

2️⃣ Compute eigenvalues & eigenvectors of 

AA^T  (gives U)

3️⃣ Singular values are the square roots of eigenvalues of 
A^TA

4️⃣ Construct 

U,Σ,V^T
 

In [29]:
import numpy as np

In [30]:
# Define a simple 3x3 matrix


A = np.array([[4,2,3],
              [3,1,4],
              [2,5,6]])

In [31]:
U,S, Vt = np.linalg.svd(A)

In [32]:
# Print the decomposed matrices

print(f'Original Matrix A: \n {A}')

print(f'\n U (Left Singular Vectors): \n {U}')

print(f'\n Singualr Values  (Diagonal of Σ): \n {S}')

print(f'\n T (Right Singular Vectors Transposed): \n {Vt}')


Original Matrix A: 
 [[4 2 3]
 [3 1 4]
 [2 5 6]]

 U (Left Singular Vectors): 
 [[-0.4806589   0.5875834   0.65093224]
 [-0.46073166  0.46237311 -0.75758659]
 [-0.74611886 -0.66404583  0.04847453]]

 Singualr Values  (Diagonal of Σ): 
 [10.47875438  2.96224118  1.19198736]

 T (Right Singular Vectors Transposed): 
 [[-0.45778994 -0.49172293 -0.7407003 ]
 [ 0.81335756 -0.56804599 -0.12559151]
 [ 0.35899561  0.65994872 -0.6599923 ]]


In [33]:
# Reconstruct the original matrix A using SVD components

S_Matrix = np.zeros((A.shape[0], A.shape[1])) # Convert S into diagonal matrix

np.fill_diagonal(S_Matrix,S)

In [34]:
A_reconstructed = U @ S_Matrix @ Vt

print(f'\n Reconstructed Matrix A: \n {A_reconstructed}')


 Reconstructed Matrix A: 
 [[4. 2. 3.]
 [3. 1. 4.]
 [2. 5. 6.]]


In [35]:
# Verify that the reconstructed matrix is close to the original

print(f' \n Reconstruction is Accurate: {np.allclose(A, A_reconstructed)}')

 
 Reconstruction is Accurate: True


 Key Takeaways from the Code

np.linalg.svd(A) decomposes A into three parts:

U (left singular vectors)

S (singular values)

Vt (right singular vectors, transposed)

We reconstruct A using U, Σ, Vᵀ:


A=U⋅Σ⋅V T

The np.allclose(A, A_reconstructed) confirms that we successfully decomposed and reconstructed the matrix.