🔹 Create a 1D tensor with 12 elements

🔹 Reshape it into 3×4 and 2×6

🔹 Try using .view() instead of .reshape()

In [22]:
import torch

In [23]:
# Create a tensor of 12 elements

A = torch.arange(12)

In [24]:
# Reshape it into 3×4

A_3x4 = A.reshape(3,4)

In [25]:
# Reshape it into 2x6

A_2x6 = A.view(2,6)

In [26]:
# Reshape it into 5x5

# A_5x5 = A.view(5,5)

In [27]:
print("\nOriginal Tensor:\n", A)

print("\nReshaped to 3x4:\n", A_3x4)

print("\nViewed as 2x6:\n", A_2x6)

# print("\nViewed as 5x5:\n", A_5x5) # Generating error because of size compatibility


Original Tensor:
 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Reshaped to 3x4:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Viewed as 2x6:
 tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
