In [13]:
import torch

In [14]:
# Creating a Scalar (0D tensor)

scalar = torch.tensor(5)

# Creating a Vector (1D tensor)

vector = torch.tensor([1,2,3])

# Creating a Matrix (2D tensor)

matrix = torch.tensor([[1,2], 
                       [3,4]])

# Creating a 3D Tensor

tensor3D = torch.tensor([[[1,2], [3,4]],
                        [[5,6],[7,8]]])

In [15]:
# Print the tensors
print("Scalar: \n", scalar)
print("\nVector:\n", vector)
print("\nMatrix:\n", matrix)
print("\n3D Tensor:\n", tensor3D)

# Checking the shape (dimensions) of each tensor
print("\nShapes:\n")
print("Scalar Shape:", scalar.shape)
print("Vector Shape:", vector.shape)
print("Matrix Shape:", matrix.shape)
print("3D Tensor Shape:", tensor3D.shape)

Scalar: 
 tensor(5)

Vector:
 tensor([1, 2, 3])

Matrix:
 tensor([[1, 2],
        [3, 4]])

3D Tensor:
 tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

Shapes:

Scalar Shape: torch.Size([])
Vector Shape: torch.Size([3])
Matrix Shape: torch.Size([2, 2])
3D Tensor Shape: torch.Size([2, 2, 2])
