In [13]:
import torch

In [14]:
# Creating a 3x3 tensor

A = torch.tensor([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])


print("Original Tensor:\n", A)

Original Tensor:
 tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])


In [15]:
# 🔹 Indexing - Selecting a single element

print("\nElement at (1,2):", A[1, 2])  # Row 1, Column 2 (zero-based indexing)


Element at (1,2): tensor(60)


In [16]:
# 🔹 Slicing - Extracting rows/columns

print('First row:\n ',A[0,:]) # First row

print("\nFirst Column:\n", A[:, 0])   # First column

print("\nMiddle Block:\n", A[0:2, 1:3])  # Extracts a submatrix


First row:
  tensor([10, 20, 30])

First Column:
 tensor([10, 40, 70])

Middle Block:
 tensor([[20, 30],
        [50, 60]])


🔎 Real-World Use Cases

✔ Extracting features from image pixels.

✔ Selecting specific words from a text sequence.

✔ Extracting sub-tensors for efficient processing in models.