In [14]:
import numpy as np

In [15]:
B = np.array([[10, 20, 30], 
              [40, 50, 60], 
              [70, 80, 90]])

print("\nOriginal NumPy Array:\n", B)


Original NumPy Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]


In [16]:
# Indexing & Slicing in NumPy

print('\nElement at (1,2):\n',B[1,2])

print('\nFirst row :\n',B[0,:])

print('\nFirst column :\n',B[:,0])

print('\nMiddle  Block :\n',B[0:2, 1:3])



Element at (1,2):
 60

First row :
 [10 20 30]

First column :
 [10 40 70]

Middle  Block :
 [[20 30]
 [50 60]]
