In [367]:
import torch

In [368]:
# Creating a 4x4 tensor

A = torch.tensor([[10, 20, 30,50],
                  [40, 50, 60,70],
                  [70, 80, 90,100],
                  [80, 90, 100,110]])


print("Original Tensor:\n", A)

A.size()

Original Tensor:
 tensor([[ 10,  20,  30,  50],
        [ 40,  50,  60,  70],
        [ 70,  80,  90, 100],
        [ 80,  90, 100, 110]])


torch.Size([4, 4])

In [369]:
print('\nThird row:\n', A[2,:])

print('Second Column:\n', A[:, 1])

print('2x2 submatrix from the center:\n', A[1:3,1:3])


Third row:
 tensor([ 70,  80,  90, 100])
Second Column:
 tensor([20, 50, 80, 90])
2x2 submatrix from the center:
 tensor([[50, 60],
        [80, 90]])


In [370]:
print('\n First 2 rows : \n', A[:2, :])

print('\n Submatrix of 1st and 3rd column:\n ', A[::2,::2])


 First 2 rows : 
 tensor([[10, 20, 30, 50],
        [40, 50, 60, 70]])

 Submatrix of 1st and 3rd column:
  tensor([[10, 30],
        [70, 90]])


In [371]:
print('\nLast 2 rows\n:', A[2:])

print('\n2x2 submatrix from the bottom-right of A: \n ', A[2:,2:])


Last 2 rows
: tensor([[ 70,  80,  90, 100],
        [ 80,  90, 100, 110]])

2x2 submatrix from the bottom-right of A: 
  tensor([[ 90, 100],
        [100, 110]])


In [372]:
print('last column of A:\n',  A[:,3])

print('every alternate row starting from the second row\n', A[1::2])

last column of A:
 tensor([ 50,  70, 100, 110])
every alternate row starting from the second row
 tensor([[ 40,  50,  60,  70],
        [ 80,  90, 100, 110]])


In [373]:
print('\nfirst two elements of every row \n:', A[:,:2])

print('\nExtract the last two columns of A\n', A[:, 2:])


first two elements of every row 
: tensor([[10, 20],
        [40, 50],
        [70, 80],
        [80, 90]])

Extract the last two columns of A
 tensor([[ 30,  50],
        [ 60,  70],
        [ 90, 100],
        [100, 110]])


In [374]:
print('\nmiddle row of A 4X4 Matrix Index 1,2 \n', A[1:3])

print('\ncorner elements (first row, first column & last row, last column\n', A[0,0],A[-1,-1])


middle row of A 4X4 Matrix Index 1,2 
 tensor([[ 40,  50,  60,  70],
        [ 70,  80,  90, 100]])

corner elements (first row, first column & last row, last column
 tensor(10) tensor(110)
