Task:

🔹 Create two (2×3) tensors

🔹 Concatenate them along rows and columns

🔹 Stack them to create a new dimension

In [12]:
import torch

In [13]:
B1 = torch.tensor([[1,2,3],[4,5,6]])

B2 = torch.tensor([[7,8,9],[10,11,12]])

In [14]:
# Concatenate along rows (axis=0)

B_cat_rows = torch.cat((B1,B2),dim=0)

In [15]:
# Concatenate along columns (axis=1)

B_cat_cols = torch.cat((B1,B2),dim=1)

In [16]:
# Stack along new dimension

B_stack = torch.stack((B1,B2), dim=0)

In [17]:
print("\nConcatenated along rows:\n", B_cat_rows)

print("\nConcatenated along columns:\n", B_cat_cols)

print("\nStacked along new dimension:\n", B_stack)


Concatenated along rows:
 tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

Concatenated along columns:
 tensor([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]])

Stacked along new dimension:
 tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
