Task:

🔹 Create a 1D tensor of 10 elements

🔹 Split into 2 parts of sizes [3, 7]

🔹 Chunk into 5 equal parts

In [26]:
import torch

In [27]:
C = torch.arange(10)

In [28]:
# Split into sizes 3 and 7

C_split = torch.split(C,[3,7])

In [29]:
# Chunk into 5 equal parts

C_chunk = torch.chunk(C, 5)

In [30]:
print("\nOriginal Tensor:\n", C)

print("\nSplit into sizes [3,7]:\n", C_split)

print("\nChunked into 5 equal parts:\n", C_chunk)


Original Tensor:
 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Split into sizes [3,7]:
 (tensor([0, 1, 2]), tensor([3, 4, 5, 6, 7, 8, 9]))

Chunked into 5 equal parts:
 (tensor([0, 1]), tensor([2, 3]), tensor([4, 5]), tensor([6, 7]), tensor([8, 9]))
