Task:

🔹 Create a (2×3) tensor

🔹 Transpose to (3×2)

🔹 Permute to (1×2×3) and (3×2×1)

In [6]:
import torch

In [7]:
D = torch.tensor([[1,2,3],[4,5,6]])

In [8]:
# Transpose rows & columns

D_T = D.T # Same as D.transpose(0,1)

In [9]:
# Permute dimensions

D_P1 = D.reshape(1,2,3)

D_P2 = D.reshape(3,2,1)

In [10]:
print("\nOriginal Tensor:\n", D)

print("\nTransposed (3x2):\n", D_T)

print("\nPermuted to (1x2x3):\n", D_P1)

print("\nPermuted to (3x2x1):\n", D_P2)


Original Tensor:
 tensor([[1, 2, 3],
        [4, 5, 6]])

Transposed (3x2):
 tensor([[1, 4],
        [2, 5],
        [3, 6]])

Permuted to (1x2x3):
 tensor([[[1, 2, 3],
         [4, 5, 6]]])

Permuted to (3x2x1):
 tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])
