In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd

from sklearn.svm import SVC

import numpy as np

import matplotlib.pyplot as plt

import os # define path of files and directories

from skimage.io import imread # used for reading images

from sklearn.model_selection import train_test_split

from skimage.transform import resize



In [ ]:
os.listdir('/content/drive/MyDrive/Data')

['Dog', 'Cat']

In [ ]:
len(os.listdir('/content/drive/MyDrive/Data/Cat'))

85

In [ ]:
len(os.listdir('/content/drive/MyDrive/Data/Dog'))

68

In [ ]:
catpath = os.path.join('/content/drive/MyDrive/Data','Cat')

for img in os.listdir(catpath):

  print(img)

cat.59.jpg
cat.40.jpg
cat.115.jpg
cat.86.jpg
cat.82.jpg
cat.112.jpg
cat.83.jpg
cat.65.jpg
cat.55.jpg
cat.93.jpg
cat.113.jpg
cat.51.jpg
cat.71.jpg
cat.76.jpg
cat.102.jpg
cat.35.jpg
cat.106.jpg
cat.95.jpg
cat.118.jpg
cat.48.jpg
cat.41.jpg
cat.68.jpg
cat.60.jpg
cat.88.jpg
cat.91.jpg
cat.78.jpg
cat.97.jpg
cat.67.jpg
cat.57.jpg
cat.37.jpg
cat.46.jpg
cat.36.jpg
cat.52.jpg
cat.96.jpg
cat.63.jpg
cat.79.jpg
cat.64.jpg
cat.42.jpg
cat.110.jpg
cat.89.jpg
cat.104.jpg
cat.84.jpg
cat.87.jpg
cat.111.jpg
cat.38.jpg
cat.45.jpg
cat.69.jpg
cat.49.jpg
cat.77.jpg
cat.58.jpg
cat.74.jpg
cat.105.jpg
cat.109.jpg
cat.66.jpg
cat.107.jpg
cat.39.jpg
cat.75.jpg
cat.61.jpg
cat.103.jpg
cat.73.jpg
cat.90.jpg
cat.100.jpg
cat.114.jpg
cat.44.jpg
cat.47.jpg
cat.94.jpg
cat.62.jpg
cat.85.jpg
cat.81.jpg
cat.99.jpg
cat.117.jpg
cat.98.jpg
cat.70.jpg
cat.108.jpg
cat.56.jpg
cat.50.jpg
cat.53.jpg
cat.101.jpg
cat.43.jpg
cat.72.jpg
cat.80.jpg
cat.119.jpg
cat.92.jpg
cat.116.jpg
cat.54.jpg


In [ ]:
dogpath = os.path.join('/content/drive/MyDrive/Data','Dog')

for img in os.listdir(dogpath):

  print(img)

dog.67.jpg
dog.32.jpg
dog.14.jpg
dog.66.jpg
dog.48.jpg
dog.5.jpg
dog.17.jpg
dog.19.jpg
dog.62.jpg
dog.49.jpg
dog.26.jpg
dog.45.jpg
dog.50.jpg
dog.1.jpg
dog.38.jpg
dog.27.jpg
dog.36.jpg
dog.68.jpg
dog.35.jpg
dog.65.jpg
dog.55.jpg
dog.46.jpg
dog.44.jpg
dog.42.jpg
dog.54.jpg
dog.13.jpg
dog.30.jpg
dog.61.jpg
dog.10.jpg
dog.52.jpg
dog.63.jpg
dog.39.jpg
dog.25.jpg
dog.60.jpg
dog.37.jpg
dog.21.jpg
dog.9.jpg
dog.64.jpg
dog.31.jpg
dog.41.jpg
dog.20.jpg
dog.3.jpg
dog.4.jpg
dog.53.jpg
dog.15.jpg
dog.22.jpg
dog.24.jpg
dog.2.jpg
dog.43.jpg
dog.12.jpg
dog.7.jpg
dog.33.jpg
dog.58.jpg
dog.11.jpg
dog.34.jpg
dog.51.jpg
dog.16.jpg
dog.23.jpg
dog.57.jpg
dog.29.jpg
dog.8.jpg
dog.28.jpg
dog.56.jpg
dog.18.jpg
dog.6.jpg
dog.40.jpg
dog.47.jpg
dog.59.jpg


In [ ]:
flat_data_arr = [] # used for collecting input data

target_arr = [] # used for collecting output data

categories = ['Cat','Dog']

datadir = '/content/drive/MyDrive/Data'

In [ ]:
for i in categories: # cat

   print('Loading Categories...........')

   path = os.path.join(datadir,i) #'/content/drive/MyDrive/Data',cat

   for img in os.listdir(path):  #for j in os.listdir(path)

      img_arr = imread(os.path.join(path,img)) # imread(os.path.join(path,img))

      img_resize = resize(img_arr,(150,150,3)) #height,width,RGB (PIXELS)

      flat_data_arr.append(img_resize.flatten()) # 1D DATA USING FLATTEN

      target_arr.append(categories.index(i)) # 0 for cat and 1 for dog

   print('Loaded completely',i)


Loading Categories...........
Loaded completely Cat
Loading Categories...........
Loaded completely Dog


In [ ]:
flat_data = np.array(flat_data_arr)

target_data = np.array(target_arr)

jarvis = pd.DataFrame(flat_data)

jarvis

0         1         2         3         4         5         6      \
0    0.570284  0.534670  0.280766  0.550254  0.511154  0.271318  0.563056   
1    0.286800  0.245944  0.250669  0.298188  0.255705  0.259413  0.288413   
2    0.200063  0.200063  0.200063  0.200063  0.200063  0.200063  0.200063   
3    0.564706  0.572549  0.521569  0.564706  0.572549  0.521569  0.564706   
4    0.478295  0.474374  0.497903  0.477381  0.473460  0.496989  0.491041   
..        ...       ...       ...       ...       ...       ...       ...   
148  0.612096  0.506214  0.470920  0.568027  0.467242  0.437046  0.544847   
149  0.621803  0.589615  0.521395  0.622976  0.597152  0.525778  0.612878   
150  0.131540  0.185830  0.340608  0.146411  0.201307  0.354267  0.161383   
151  0.161774  0.094111  0.140884  0.134132  0.084561  0.131425  0.150611   
152  0.480507  0.470286  0.532080  0.455931  0.447696  0.501620  0.419735   

        7         8         9      ...     67490     67491     67492  \
0    0.518567  0.304325  0.572157  ...  0.571616  0.715383  0.680025   
1    0.241201  0.236668  0.300227  ...  0.342341  0.309882  0.260066   
2    0.200063  0.200063  0.200063  ...  0.148465  0.027277  0.125513   
3    0.572549  0.521569  0.564706  ...  0.112709  0.156976  0.129525   
4    0.487119  0.510649  0.499533  ...  0.544947  0.576333  0.541039   
..        ...       ...       ...  ...       ...       ...       ...   
148  0.447135  0.420694  0.409511  ...  0.361312  0.395262  0.348204   
149  0.597833  0.523429  0.608727  ...  0.460397  0.551879  0.532271   
150  0.223393  0.366578  0.169894  ...  0.118748  0.093208  0.023828   
151  0.104154  0.153375  0.150425  ...  0.069131  0.112697  0.060094   
152  0.412040  0.460354  0.410372  ...  0.292166  0.310620  0.275325   

        67493     67494     67495     67496     67497     67498     67499  
0    0.518856  0.717773  0.684738  0.509660  0.702145  0.670557  0.488359  
1    0.246458  0.443168  0.358662  0.317528  0.519170  0.417826  0.339939  
2    0.144992  0.015270  0.125065  0.140691  0.007791  0.120407  0.136030  
3    0.105994  0.157180  0.129729  0.104476  0.162190  0.134739  0.098832  
4    0.544960  0.562095  0.526801  0.530722  0.541868  0.506574  0.510496  
..        ...       ...       ...       ...       ...       ...       ...  
148  0.348204  0.372594  0.325535  0.325535  0.386530  0.339471  0.339471  
149  0.453840  0.564501  0.544059  0.466253  0.579663  0.546425  0.478216  
150  0.017193  0.134098  0.063522  0.055692  0.102538  0.033174  0.026556  
151  0.088773  0.092280  0.042923  0.066505  0.102710  0.061549  0.071227  
152  0.294935  0.324187  0.288069  0.310150  0.322614  0.283509  0.314549  

[153 rows x 67500 columns]

In [ ]:
jarvis['Target']=target_arr

jarvis

0         1         2         3         4         5         6  \
0    0.570284  0.534670  0.280766  0.550254  0.511154  0.271318  0.563056   
1    0.286800  0.245944  0.250669  0.298188  0.255705  0.259413  0.288413   
2    0.200063  0.200063  0.200063  0.200063  0.200063  0.200063  0.200063   
3    0.564706  0.572549  0.521569  0.564706  0.572549  0.521569  0.564706   
4    0.478295  0.474374  0.497903  0.477381  0.473460  0.496989  0.491041   
..        ...       ...       ...       ...       ...       ...       ...   
148  0.612096  0.506214  0.470920  0.568027  0.467242  0.437046  0.544847   
149  0.621803  0.589615  0.521395  0.622976  0.597152  0.525778  0.612878   
150  0.131540  0.185830  0.340608  0.146411  0.201307  0.354267  0.161383   
151  0.161774  0.094111  0.140884  0.134132  0.084561  0.131425  0.150611   
152  0.480507  0.470286  0.532080  0.455931  0.447696  0.501620  0.419735   

            7         8         9  ...     67491     67492     67493  \
0    0.518567  0.304325  0.572157  ...  0.715383  0.680025  0.518856   
1    0.241201  0.236668  0.300227  ...  0.309882  0.260066  0.246458   
2    0.200063  0.200063  0.200063  ...  0.027277  0.125513  0.144992   
3    0.572549  0.521569  0.564706  ...  0.156976  0.129525  0.105994   
4    0.487119  0.510649  0.499533  ...  0.576333  0.541039  0.544960   
..        ...       ...       ...  ...       ...       ...       ...   
148  0.447135  0.420694  0.409511  ...  0.395262  0.348204  0.348204   
149  0.597833  0.523429  0.608727  ...  0.551879  0.532271  0.453840   
150  0.223393  0.366578  0.169894  ...  0.093208  0.023828  0.017193   
151  0.104154  0.153375  0.150425  ...  0.112697  0.060094  0.088773   
152  0.412040  0.460354  0.410372  ...  0.310620  0.275325  0.294935   

        67494     67495     67496     67497     67498     67499  Target  
0    0.717773  0.684738  0.509660  0.702145  0.670557  0.488359       0  
1    0.443168  0.358662  0.317528  0.519170  0.417826  0.339939       0  
2    0.015270  0.125065  0.140691  0.007791  0.120407  0.136030       0  
3    0.157180  0.129729  0.104476  0.162190  0.134739  0.098832       0  
4    0.562095  0.526801  0.530722  0.541868  0.506574  0.510496       0  
..        ...       ...       ...       ...       ...       ...     ...  
148  0.372594  0.325535  0.325535  0.386530  0.339471  0.339471       1  
149  0.564501  0.544059  0.466253  0.579663  0.546425  0.478216       1  
150  0.134098  0.063522  0.055692  0.102538  0.033174  0.026556       1  
151  0.092280  0.042923  0.066505  0.102710  0.061549  0.071227       1  
152  0.324187  0.288069  0.310150  0.322614  0.283509  0.314549       1  

[153 rows x 67501 columns]

In [ ]:
x = jarvis.iloc[:,:-1].values

x

array([[0.57028429, 0.5346697 , 0.28076608, ..., 0.70214514, 0.67055703,
        0.48835908],
       [0.28680013, 0.24594407, 0.25066917, ..., 0.51916953, 0.41782577,
        0.3399393 ],
       [0.20006338, 0.20006338, 0.20006338, ..., 0.00779116, 0.12040675,
        0.13602965],
       ...,
       [0.13154044, 0.18583007, 0.34060824, ..., 0.102538  , 0.03317442,
        0.02655595],
       [0.16177408, 0.09411126, 0.140884  , ..., 0.10271019, 0.06154931,
        0.0712269 ],
       [0.48050656, 0.47028585, 0.53208013, ..., 0.32261393, 0.28350908,
        0.31454912]])

In [ ]:
y = jarvis.iloc[:,-1]

y

0      0
1      0
2      0
3      0
4      0
      ..
148    1
149    1
150    1
151    1
152    1
Name: Target, Length: 153, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

train_x,test_x,train_y,test_y = train_test_split(x,y,test_size=0.20,random_state=42)

train_x

array([[0.11764706, 0.12548947, 0.11683148, ..., 0.15036089, 0.21702755,
        0.24447854],
       [0.05864819, 0.05864819, 0.09002074, ..., 0.14035102, 0.1065987 ,
        0.11002968],
       [0.11413595, 0.0945281 , 0.0827634 , ..., 0.46845752, 0.4331634 ,
        0.4449281 ],
       ...,
       [0.56776869, 0.51286673, 0.46188634, ..., 0.73222941, 0.6538657 ,
        0.60020858],
       [0.0543247 , 0.0543247 , 0.04648156, ..., 0.04945859, 0.04945859,
        0.04357953],
       [0.33905008, 0.36784105, 0.42370379, ..., 0.61269059, 0.44406313,
        0.30680823]])

In [ ]:
from sklearn.svm import SVC

hydra = SVC()

hydra.fit(train_x,train_y)

y_pred = hydra.predict(test_x)

y_pred


array([0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0])

In [ ]:
from sklearn.metrics import accuracy_score

print('Accuracy_score:',accuracy_score(test_y,y_pred))

Accuracy_score: 0.5806451612903226


In [ ]:
path1 = '/content/drive/MyDrive/GettyImages-181861505-4e63227ed0a14dc9bfe86848ef54caf3.jpg'

img = imread(path1)

img=resize(img,(150,150,3)).flatten().reshape(1,-1)

hydra.predict(img)

array([0])

In [ ]:
path2 = '/content/drive/MyDrive/unnamed.png'

img = imread(path2)

img=resize(img,(150,150,3)).flatten().reshape(1,-1)

hydra.predict(img)

array([0])